### ISSUE TITLE
Deployment Documentation for Tenbeo Auth

### ISSUE THREAD

**Issue by bobblessinghartley** [Tenbeo/Tenbeo-Auth#4]

**Comment by bobblessinghartley** [comment]
@GeorgiosDelkos When we get ready for initial deployments we will need to have basic installation instructions.

**Comment by GeorgiosDelkos** [comment]
@bobblessinghartley we have full documentation for the installation of Tenbeo-Auth at [](https://github.com/Tenbeo/Tenbeo-Auth/tree/main/docs)
